# Build to the "latest"
name: Documentation
on:
  push:
    branches:
      - gh-actions


jobs:
  Latest-Docs:
    name: Build and deploy latest documentation
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: website-test
      DEPLOY_NAME: latest
      DEPLOYNAME: latesttt
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.8"
          environment-file: environment-dev.yml
      - name: Conda Info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Sphinx Build
        # login shell should be used so conda activate runs
        shell: bash -l {0}
        run: sphinx-build -b html docs docs/_build/html
      - name: Copy Documentation to ${{ github.sha }}
        run: |
          mkdir -p docs/$DEPLOY_NAME
          # clean any existing contents
          rm -rf docs/$DEPLOY_NAME/*
          # copy the output
          cp -Rf docs/_build/html/* docs/$DEPLOY_NAME
      - name: Commit and push changes
        run: |
          git checkout $TARGET_BRANCH
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/$DEPLOY_NAME
          git commit -m "DOC&#58; Deploy ${DEPLOY_NAME} docs to website&#58; ${{ github.sha }}"
          git push
