# Build to the "latest"
name: Documentation
on:
  push:
    branches:
      - gh-actions
jobs:
  Latest-Docs:
    name: Build and deploy ${{ env.DEPLOY_NAME }} documentation
    runs-on: ubuntu-latest
    needs: Tests
    env:
      TARGET_BRANCH: website-test
      DEPLOY_NAME: latest
    steps:
      - uses: actions/checkout@v2
      - name: Sphinx Build
        run: sphinx-build -b html docs docs/_build/html
      - name: Copy Documentation to ${{ env.DEPLOY_NAME }}
        run: |
          mkdir -p docs/$DEPLOY_NAME
          # clean any existing contents
          rm -rf docs/$DEPLOY_NAME/*
          # copy the output
          cp -Rf docs/_build/html/* docs/$DEPLOY_NAME
      - name: Commit and push changes
        run:
          git checkout $TARGET_BRANCH
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/$DEPLOY_NAME
          git commit -m 'DOC&#58; Deploy docs to website&#58;'
          git push
