name: pytest

on: [push]

jobs:
  Tests:
    name: Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 9
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8"]
        # python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch the entire repo history, required to guarantee versioneer will pick up the tags
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda info
          conda install -c conda-forge -c pycalphad "cyipopt" "cython>=0.24" "matplotlib" "numpy>=1.13" "pyparsing" "python-symengine=0.6.1" "python>=3.6" "scipy" "symengine=0.6.0" "sympy=1.5.1" "tinydb>=3.8" "xarray>=0.11.2"
      - name: Install pycalphad development version
        shell: bash -l {0}
        run: |
          pwd
          ls -al
          pwd
          pip install --no-deps -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          # coverage<5, see https://github.com/coveralls-clients/coveralls-python/issues/213
          conda install -c conda-forge "pytest" "pytest-cov" "coveralls" "coverage<5"
          conda list
          pytest -v --cov=pycalphad


