name: pycalphad tests

on: [push]

jobs:
  Tests:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      max-parallel: 9
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetch the entire repo history, required to guarantee versioneer will pick up the tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Install pycalphad development version
      run: |
        $CONDA/bin/pip install --no-deps -e .
    - name: Test with pytest
      run: |
        # coverage<5, see https://github.com/coveralls-clients/coveralls-python/issues/213
        conda install pytest pytest-cov coveralls "coverage<5"
        conda list
        $CONDA/bin/pytest -v --cov=pycalphad
