name: Tests

on: [push]

jobs:
  Tests:
    name: Test ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 9
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch the entire repo history, required to guarantee versioneer will pick up the tags
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment-test.yml
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      # The last conda-forge Python 3.6 build uses an old macOS deployment
      # target that causes C++ builds to break. This is a workaround. See
      # https://github.com/pycalphad/pycalphad/pull/285#issuecomment-731365552
      - name: macOS + Python 3.6 deployment target fix
        if: matrix.os == 'macos-latest' && matrix.python-version == '3.6'
        shell: bash -l {0}
        run: |
          export MACOSX_DEPLOYMENT_TARGET="10.9"
          echo "!! deployment target (in the fix step)"
          echo $MACOSX_DEPLOYMENT_TARGET
      - name: Install pycalphad development version
        shell: bash -l {0}
        run: |
          echo "!! deployment target"
          echo $MACOSX_DEPLOYMENT_TARGET
          pip install --no-deps -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest -v --cov=pycalphad


